### PR TITLE
Add support for flags of type string

### LINKED ISSUE #10: Add string type to Flag
Currently only `bool` type is supported. Add support for `string` as well. Reference: http://godoc.org/github.com/jingweno/gotask/tasking#Flags

### PR DESCRIPTION
**Pull request by remogatto**
This PR should fix jingweno/gotask#10

### CODE REVIEW

**Comment by owenthereal** [comment]
Thanks for the contribution @remogatto. Just a quick note that I'm looking at this and will provide feedback pretty soon :smile_cat:

**Comment by remogatto** [comment]
:thumbsup: Consider that mine is a quick hack so feel free to fix it!

**Comment by owenthereal** [comment]
I've done some work to support the string flag: https://github.com/remogatto/gotask/commit/2ab52cde3057fc1582dae3a8fdaedcfcea0e2f24. But I haven't figured out what format to show for a string flag as the man page in the comment. I'd like use the same format as standard man page.

I have seen `git` uses format like `--flag <value>`. I have also seen other tools use `--flag=value`. I need to do some research on the format. I welcome all suggestions.

**Comment by remogatto** [comment]
I don't think there is a standard for this. <tt>ls</tt> use the uppercase without quote: <tt>--ignore=PATTERN</tt>.

**Comment by owenthereal** [comment]
I merged the branch in https://github.com/jingweno/gotask/commit/9649e4c35b4898e6c873e8e1b7ddc6b73eef9e41. I end up following the [POSIX convention](http://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html). See [the godoc](http://godoc.org/github.com/jingweno/gotask/tasking#hdr-Flags) for the usage. Let me know if you have any suggestion

**Pull request closed without merging**
